### ISSUE TITLE
[Feature]: add support for Gumbel Distribution

### ISSUE THREAD

**Issue by wiseaidev** [statrs-dev/statrs#189]
Hey everyone! I have been using this library for quite a while now, and I noticed that It doesn't support some distribution functions like Exponential and [Gumbel](https://en.wikipedia.org/wiki/Gumbel_distribution). I think one way to add support for missing distributions is by migrating from [rand](https://docs.rs/rand/latest/rand/) to [rand_distr](https://rust-random.github.io/rand/rand_distr/index.html). What do you think?

**Edit 1**: I am thinking about a relationship between, for instance, Poisson and Exponential Distributions. Probably there is one and I can compute one from another. Know what I am saying?

**Edit 2**: Oh, wait! It is called [Exp](https://docs.rs/statrs/latest/statrs/distribution/struct.Exp.html).

**Comment by YeungOnion** [comment]
This could be useful.

This distribution would probably need to implement the following traits
- derive
  - `Debug`
  - `Copy`
  - `Clone`
  - `PartialEq`
- `distribution::Continuous<f64, f64>`
- `distribution::ContinuousCDF<f64, f64>`
- `statistics::{Min, Max, Mean, Median, Mode} `
- `::rand::distributions::Distribution<f64>`
- `statistics::Distribution`
 
all methods seem like they should be based on closed form expressions, perhaps with considerations for numerical stability of
- double exponential, especially with `pdf`
- double logarithms, if directly using them in `inverse_cdf`

**Comment by YeungOnion** [comment]
Since it wasn't straightforward to find the exponential distribution as `Exp` could be a short PR to add a doc alias for "exponential". See [rustdoc docs on `#[doc]`](https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#alias) and in our crate, #174 and eb0745e46d74a077fce9345ee772598aa6183671

**Comment by soumyasen1809** [comment]
Hi @YeungOnion I am new to Rust and would want to take a shot at this issue. Is it possible to work on adding Gumbel distribution?

**Comment by YeungOnion** [comment]
Absolutely! Feel free to ping me here for any help. Also, as you're new, I'd like to mention the [Rust Language forum](https://users.rust-lang.org/).


For consistency, I request that the error type you create for this distribution should have an error message from `Display` with language that describes the unexpected input, as opposed to what it is not. Some truncated examples from other error messages in the project.
- `"is NAN or is outside [0,1]"` instead of `"must be on [0,1]"`
- `"shape and scale are both inf"` instead of `"must have finite shape or finite scale"`

**Comment by soumyasen1809** [comment]
@YeungOnion I have a PR for this issue
https://github.com/statrs-dev/statrs/pull/285

**Comment by YeungOnion** [comment]
Closed by #285
