### ISSUE TITLE
tracker: 0.17 release

### ISSUE THREAD

**Issue by YeungOnion** [statrs-dev/statrs#205]
list of items to add to the new release since changing maintainer(s)

# Targeted
- [x] no distribute NIST data
- [x] nalgebra update
- [x] changelog updates
- [x] corrections to docs
- [x] various fixes

# Future
- review CI, #207 
- consistent multivariate API with nalgebra
  - feature for `multivariate_nalgebra`
- data driven distributions?
- more effective errors (and panics?)

**Comment by FreezyLemon** [comment]
Note that while the NIST dataset is still in the repo, #214 at least removed it from the crates.io package. So the remaining part of the issue should not be a blocker for a new package version/release.

The CI changes don't need to be a version blocker either, they're almost exclusively non-functional changes (formatting, code style). On the other hand, they're relatively easy to fix.

I guess it would be nice to have a consistent `nalgebra` API, but IMHO, I'm not sure it's worth holding back a release for. This is subjective, but the current API is not broken or untenable and a new release could be productive for these API discussions because of renewed attention on the project. ATM, it's only a small amount of people participating in these API-related discussions.

**Comment by YeungOnion** [comment]
More input from users would be beneficial for the discussion on API. Thanks for the suggestion, and I think I'll take it.
