### ISSUE TITLE
Change compile requirements for running `cargo test`

### ISSUE THREAD

**Issue by YeungOnion** [statrs-dev/statrs#233]
Do we _need_ the nightly compiler just for the test suite? The requirement is for feature `fn_traits` (I believe this requires  feature `unboxed_closures`) is from `statrs::testing_boiler` but nowhere else.

Feedback seems to be,
- non-obvious to test with nightly for new contributors (even when familiar with rust projects) 
- assertion error messages reference call to macro `statrs::testing_boiler`, not clear what line test is defined on.

Open to other feedback, but what I'm imagining is a few proc macros that expand to unwraps or assertions
- `create(dist_family_name, tuple_of_dist_parameters, ...error msg)`
- `bad_create(...` sim to previous asserting is_err
- `test_almost(dist_family_name, tuple_of_dist_parameters, dot_method_call_with_args, ...error_msg)`

**Comment by FreezyLemon** [comment]
Related: #232 

I'm pretty sure the `testing_boiler` macro can be changed so that it doesn't need any nightly compiler features. 

I wonder about the second part. Does `RUST_BACKTRACE=1` not give any useful information? How would an optional error message, e.g. in `test_almost(/* .. */, "error message here")`, help with [test suites like these](https://github.com/statrs-dev/statrs/blob/358aafb58bd25038a2379aefa3249ecb62037228/src/distribution/cauchy.rs#L360-L392)? There must be a better way than adding error messages "line 1", "line 2", ..., right?

**Comment by YeungOnion** [comment]
`RUST_BACKTRACE=1` does provide useful info, perhaps I'm a little silly. I think the messages would be convenient, but I think changing what we have for existing would be better.

**Comment by YeungOnion** [comment]
resolved by #234
